---
version: "2"
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-74 # Minimum version to support ruby 2.6
  eslint:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby

ratings:
  paths:
  - lib/**
  - "**.rb"

exclude_paths:
- spec/**/*
- "**/vendor/**/*"
