language: ruby
cache: bundler
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - 2.2.2
  - 2.2.3
  - 2.3.0
  - 2.3.1
before_install:
- "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
script:
  - bundle exec rspec
notifications:
  email: false